name: CI

on: [push]

jobs:
  generateTOC:
    runs-on: ubuntu-latest
    name: Generate Table of Contents
    steps:
      - name: TOC Generator
        uses: technote-space/toc-generator@v2.0.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test-courses-cpp-ctf-segv-actual:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Login to docker
      run: docker login docker.pkg.github.com -u github-actions -p ${{ secrets.GITHUB_TOKEN }}

    - name: Build Images & Run Queries
      run: cd courses/cpp/ctf-segv && ../../../scripts/test-course-actual.sh
  test-courses-cpp-ctf-segv-latest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build Images & Run Queries
      run: cd courses/cpp/ctf-segv && ../../../scripts/test-course-latest.sh
  test-courses-template-actual:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Login to docker
      run: docker login docker.pkg.github.com -u github-actions -p ${{ secrets.GITHUB_TOKEN }}

    - name: Build Images & Run Queries
      run: cd templates/action && ../../scripts/test-course-actual.sh
  test-courses-template-latest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build Images & Run Queries
      run: cd templates/action && ../../scripts/test-course-latest.sh
